parameters:
#    acme_reservas.example.class: Acme\ReservasBundle\Example

services:
#    acme_reservas.example:
#        class: %acme_reservas.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
